"use client";
import {useState} from "react";
import {Moon,Shuffle,Check,Heart,Clock3,Users,ChevronDown,Copy,ShoppingBasket,Undo2,Maximize2,Scissors,Flame,Utensils} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Empty} from "@/components/ui/empty";
import {toast} from "sonner";
import {Check as CheckRow} from "./controls";
import type {AppData,Dinner} from "@/lib/types";
import type {SaveData} from "./parent-panel";
import {allowedDinners,rankDinners,dinnerById,menuText,recipePrompt,shoppingText} from "@/lib/dinners";
import {dayLabel} from "@/lib/dates";
async function copy(text:string){try{await navigator.clipboard.writeText(text);toast.success("コピーしました");}catch{toast.error("コピーできませんでした。表示された文章を選択してコピーしてください。");}}
function RecipePoster({m}:{m:Dinner}){return <div className="recipe-poster"><img src={m.image} alt={`${m.main}と${m.side}の盛りつけ例`}/><div className="poster-heading"><span>OUR EVERYDAY TABLE</span><h3>{m.title}</h3><p>4人分 · 約{m.time}分</p></div><div className="poster-steps">{m.stepLabels.map((step,i)=><div key={step}><span>{["①","②","③"][i]}</span>{i===0?<Scissors/>:i===1?<Flame/>:<Utensils/>}<p>{step}</p></div>)}</div></div>;}
export default function DinnerView({data,today,save,onSettings}:{data:AppData;today:string;save:SaveData;onSettings:()=>void}){
 const[working,setWorking]=useState(false);const[poster,setPoster]=useState(false);const[detail,setDetail]=useState(false);const[exhausted,setExhausted]=useState(false);
 const selection=data.suggestions[today];const pool=allowedDinners(data,today);const m=selection&&pool.find(x=>x.id===selection.id);const chosen=data.dinner[today];
 async function alternate(restart=false){setWorking(true);let found=false;await save(d=>{const s=d.suggestions[today];if(!s)return d;const next=rankDinners(d,today).find(x=>x.id!==s.id&&(restart||!s.seen.includes(x.id)));if(!next)return d;found=true;return{...d,suggestions:{...d.suggestions,[today]:{id:next.id,seen:restart?[s.id,next.id]:[...s.seen,next.id],trail:[...s.trail,s.id].slice(-99)}}};});setExhausted(!found);setWorking(false);if(found)toast("別のメニューを選んだよ");}
 async function previous(){setWorking(true);await save(d=>{const s=d.suggestions[today];if(!s)return d;const allowed=allowedDinners(d,today);const trail=[...s.trail];let id:string|undefined;while(trail.length){const p=trail.pop()!;if(allowed.some(x=>x.id===p)&&p!==s.id){id=p;break;}}return id?{...d,suggestions:{...d.suggestions,[today]:{...s,id,trail}}}:d;});setExhausted(false);setWorking(false);}
 async function choose(){if(!m)return;setWorking(true);const ok=await save(d=>{if(!allowedDinners(d,today).some(x=>x.id===m.id))throw Error("今の条件では選べません。設定を確認してください。");return{...d,dinner:{...d.dinner,[today]:m.id}};});if(ok)toast.success("きょうの ゆうごはん、きまり！");setWorking(false);}
 return <><div className="section-eyebrow"><Moon size={18}/>おうちで いただきます</div><div className="title-row dinner-title"><h1>きょうの ゆうごはん</h1><span className="tiny-label">DINNER TIME</span></div><div className="dinner-day"><span>{dayLabel(today)}</span><span>4人分のこんだて</span></div>
 {!m?<Empty className="empty-state"><h2>{pool.length?"メニューを準備しています":"条件に合うメニューがありません"}</h2><p>使わない食材や、今週の夕食を確認してください。</p><button className="secondary-button" onClick={onSettings}>おうちの設定を開く</button></Empty>:<>
 <div className="recommend-label"><span>きょうは、これにしよう！</span><p>今日のおすすめメニューはこれ！</p></div>
 <article className="dinner-card" aria-live="polite"><button className="dinner-photo-button" onClick={()=>setPoster(true)} aria-label="レシピ画像を大きく見る"><img className="dinner-photo" src={m.image} alt={`${m.main}と${m.side}`}/><span className="photo-expand"><Maximize2 size={15}/>レシピ画像</span></button><div className="dinner-card-body"><div className="dinner-card-top"><span className="recipe-no">TODAY’S RECIPE</span><button className={`favorite-button ${data.favorites.includes(m.id)?"active":""}`} aria-label={data.favorites.includes(m.id)?"お気に入りを外す":"お気に入りにする"} aria-pressed={data.favorites.includes(m.id)} onClick={()=>void save(d=>({...d,favorites:d.favorites.includes(m.id)?d.favorites.filter(x=>x!==m.id):[...d.favorites,m.id]}))}><Heart size={23} fill={data.favorites.includes(m.id)?"currentColor":"none"}/></button></div><h2>{m.reading}</h2><p className="dinner-formal-name">{m.main}</p><div className="side-dish"><span>おやさい</span><p>{m.side}</p></div><div className="recipe-meta"><span><Clock3 size={17}/>約{m.time}分</span><span><Users size={17}/>4人分</span>{m.weeklyLimited&&<span className="week-tag">週1メニュー</span>}</div><p className="helper">炊いたごはん・冷凍ごはんを使います。</p><div className="dinner-actions"><button className="primary-button full" onClick={()=>void choose()} disabled={working||chosen===m.id}><Check size={21}/>{chosen===m.id?"きょうは これに きまり！":"今日はこれにする"}</button><button className="secondary-button full" onClick={()=>void alternate()} disabled={working||pool.length<2}><Shuffle size={20}/>別のメニュー</button><button className="text-button previous-button" onClick={()=>void previous()} disabled={working||!selection?.trail.length}><Undo2 size={16}/>前のメニュー</button></div></div></article>
 {exhausted&&<div className="info-box exhaustion"><p>今日の条件に合うメニューを、ひととおり見たよ。</p>{pool.length>1&&<button className="text-button" onClick={()=>void alternate(true)}>もう一度、ほかの候補を見る</button>}</div>}
 {chosen&&chosen!==m.id&&<p className="decided-note"><Check size={17}/>決定済み：{dinnerById(chosen)?.main??"カレー・シチュー"}<br/>「今日はこれにする」を押すと変更します。</p>}
 <p className="illustration-note">写真は盛りつけのイメージです。調理時間は目安です。</p>
 <button className="detail-toggle" onClick={()=>setDetail(!detail)} aria-expanded={detail}><span><Utensils size={19}/>つくり方・買い物リスト</span><ChevronDown className={detail?"rotate":""}/></button>
 {detail&&<div className="recipe-details"><section className="recipe-section"><div className="section-heading"><h3>① 献立とつくり方</h3><button className="text-button" onClick={()=>void copy(menuText(m)+"\n\n"+m.steps.map((s,i)=>`${i+1}. ${s}`).join("\n"))}><Copy size={16}/>コピー</button></div><pre className="menu-output">{menuText(m)}</pre><ol className="recipe-step-list">{m.steps.map((step,i)=><li key={i}><span className="step-number">{i+1}</span><div><h4>{m.stepLabels[i]}</h4><p>{step}</p></div></li>)}</ol><p className="helper">肉の中心まで火が通ったことを確認してください。加熱時間は機器や食材の厚さに合わせて調整します。</p></section><section className="recipe-section"><div className="section-heading"><h3>② 画像生成プロンプト</h3><button className="text-button" onClick={()=>void copy(recipePrompt(m))}><Copy size={16}/>コピー</button></div><p className="helper">A4縦の料理雑誌風。コピーして画像生成に使えます。</p><details className="prompt-details"><summary>プロンプトを表示</summary><textarea readOnly value={recipePrompt(m)} rows={11} aria-label="画像生成プロンプト"/></details></section><section className="recipe-section"><div className="section-heading"><h3><ShoppingBasket size={20}/>③ 買い物リスト</h3><button className="text-button" onClick={()=>void copy(shoppingText(m))}><Copy size={16}/>コピー</button></div><p className="helper">大人2人＋小学生2人の目安。家にあるものにチェック。</p>{(["野菜","肉","その他"]as const).map(group=><div className="shopping-group" key={group}><h4>【{group}】</h4>{m.ingredients.filter(i=>i.category===group).map(i=><CheckRow key={i.name} checked={(data.shopping[`${today}/${m.id}`]??[]).includes(i.name)} onChange={b=>void save(d=>{const k=`${today}/${m.id}`,list=d.shopping[k]??[];return{...d,shopping:{...d.shopping,[k]:b?[...list,i.name]:list.filter(x=>x!==i.name)}};})}><span className="shopping-item"><span>{i.name}</span><strong>{i.amount}</strong></span></CheckRow>)}</div>)}</section></div>}
 <Dialog open={poster} onOpenChange={setPoster}><DialogContent className="poster-dialog"><DialogTitle className="sr-only">{m.title}</DialogTitle><DialogDescription className="sr-only">A4縦の料理写真と3つの手順</DialogDescription><RecipePoster m={m}/></DialogContent></Dialog>
 </>}
 </>;
}
