"use client";
import {useEffect,useRef,useState} from "react";
import type {PDFDocumentProxy} from "pdfjs-dist";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Progress} from "@/components/ui/progress";
import {Upload,FileText,CheckCircle2,Plus,Trash2,ArrowUp,ArrowDown,ImagePlus,Search,ChevronLeft,ChevronRight} from "lucide-react";
import {Choice,Check,Confirm} from "./controls";
import {FoodImage} from "./food-image";
import {openPdf,extractPdf} from "@/lib/pdf";
import {foodCatalog,findArt,kana,normalized} from "@/lib/food-art";
import {fileDataURL,readPhoto} from "@/lib/storage";
import {todayJapan,monthDays,dayLabel,dateObj,validDate} from "@/lib/dates";
import type {AppData,Dish,LunchDay,LunchMonth} from "@/lib/types";
const blank=(date:string):LunchDay=>({date,status:"unknown",dishes:[],milk:null,event:"",confirmed:false});
function PdfCanvas({doc,pageNumber,zoom}:{doc:PDFDocumentProxy;pageNumber:number;zoom:number}){const ref=useRef<HTMLCanvasElement>(null);const [error,setError]=useState("");useEffect(()=>{let cancelled=false;let task:{cancel:()=>void}|undefined;const run=async()=>{try{const page=await doc.getPage(pageNumber);if(cancelled||!ref.current)return;const viewport=page.getViewport({scale:zoom});const canvas=ref.current;canvas.width=viewport.width;canvas.height=viewport.height;task=page.render({canvas,viewport});await (task as unknown as {promise:Promise<void>}).promise;}catch(e){if(!cancelled)setError("原本を表示できませんでした。");}};void run();return()=>{cancelled=true;task?.cancel();};},[doc,pageNumber,zoom]);return <>{error&&<p role="alert">{error}</p>}<canvas ref={ref} aria-label={`献立PDF 原本 ${pageNumber}ページ`} /></>;}
export default function LunchImport({open,onClose,data,onSave,existing}:{open:boolean;onClose:()=>void;data:AppData;onSave:(month:LunchMonth,images:Record<string,string>)=>Promise<boolean>;existing?:LunchMonth}){
 const [month,setMonth]=useState(existing?.key??todayJapan().slice(0,7));const[file,setFile]=useState<File|null>(null);const[pdfURL,setPdfURL]=useState<string|undefined>(existing?.pdf);const[doc,setDoc]=useState<PDFDocumentProxy|null>(null);const[days,setDays]=useState<Record<string,LunchDay>>(existing?.days??{});const[stage,setStage]=useState<"file"|"review">(existing?"review":"file");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[warnings,setWarnings]=useState<string[]>([]);const[selected,setSelected]=useState(existing?Object.keys(existing.days)[0]:"");const[zoom,setZoom]=useState(.65);const[page,setPage]=useState(1);const[viewPDF,setViewPDF]=useState(false);const[images,setImages]=useState<Record<string,string>>({...data.images});const[artPick,setArtPick]=useState<{date:string;dish:string}|null>(null);const[query,setQuery]=useState("");const[confirm,setConfirm]=useState(false);const[cancelConfirm,setCancelConfirm]=useState(false);const fileInput=useRef<HTMLInputElement>(null);const docRef=useRef<PDFDocumentProxy|null>(null);
 useEffect(()=>()=>{void docRef.current?.loadingTask.destroy();},[]);
 useEffect(()=>{if(existing?.pdf){const bytes=Uint8Array.from(atob(existing.pdf.split(",")[1]),c=>c.charCodeAt(0));void openPdf(bytes).then(d=>{docRef.current=d;setDoc(d);}).catch(()=>setWarnings(["保存した原本を開けませんでした。献立は編集できます。"]));}},[existing]);
 const chosen=days[selected];
 const patchDay=(date:string,patch:Partial<LunchDay>)=>setDays(d=>({...d,[date]:{...(d[date]??blank(date)),...patch}}));
 const patchDish=(date:string,id:string,patch:Partial<Dish>)=>setDays(d=>({...d,[date]:{...d[date],confirmed:false,dishes:d[date].dishes.map(x=>x.id===id?{...x,...patch}:x)}}));
 async function selectFile(f:File){setError("");setBusy(true);try{
 const document=await openPdf(f);await docRef.current?.loadingTask.destroy();docRef.current=document;setDoc(document);setFile(f);
 const url=await fileDataURL(new Blob([await f.arrayBuffer()],{type:"application/pdf"}));setPdfURL(url);
 const firstPage=await document.getPage(1);const text=await firstPage.getTextContent();
 const title=text.items.filter(x=>"str"in x&&x.transform[5]>firstPage.view[3]*.915).map(x=>"str"in x?x.str:"").join("").normalize("NFKC");
 const found=title.match(/(\d{1,2})(?:がつ|月)/);let year=Number(todayJapan().slice(0,4));
 const explicit=title.match(/(20\d{2})年/);const reiwa=title.match(/令和(\d+|元)年/);
 if(explicit)year=Number(explicit[1]);else if(reiwa)year=2018+(reiwa[1]==="元"?1:Number(reiwa[1]));
 else try{const meta=await document.getMetadata();const y=(meta.info as {CreationDate?:string})?.CreationDate?.match(/^D:(\d{4})/);if(y)year=Number(y[1]);}catch{}
 if(!found)throw Error("対象月が読み取れませんでした。年月を指定して読み取るか、手入力できます。");
 const monthNumber=Number(found[1]);let key=`${year}-${String(monthNumber).padStart(2,"0")}`;setMonth(key);
 let result;const candidates=explicit||reiwa?[year]:[year,year-1,year+1,year-2,year+2];let lastError:unknown;
 for(const candidate of candidates){try{result=await extractPdf(document,candidate,monthNumber);key=`${candidate}-${String(monthNumber).padStart(2,"0")}`;break;}catch(e){lastError=e;if(!(e instanceof Error&&e.message.includes("曜日")))throw e;}}
 if(!result)throw lastError;setMonth(key);
 if(!result.supported||!Object.values(result.days).some(d=>d.status==="meal")||Object.values(result.days).some(d=>d.status==="unknown"))throw Error("このPDFは自動で登録できませんでした。年月を指定して読み取るか、手入力できます。");
 const filled:Record<string,LunchDay>={};for(const date of monthDays(key)){const day=result.days[date]??blank(date);filled[date]={...day,confirmed:day.status!=="unknown",dishes:day.dishes.map(x=>({...x,image:images[normalized(x.name)]}))};}
 const original=data.months[key];const previous=original?{key:original.key,name:original.name,pdf:original.pdf,days:original.days,importedAt:original.importedAt}:undefined;
 const success=await onSave({key,name:f.name,pdf:url,days:filled,importedAt:new Date().toISOString(),previous},images);
 if(success)onClose();else setError("保存できませんでした。もう一度ファイルを選んでください。");
 }catch(e){setError(e instanceof Error?e.message:"読み取りに失敗しました。");}finally{setBusy(false);}}

 async function parse(){if(!doc)return;setBusy(true);setError("");try{const[y,m]=month.split("-").map(Number);if(y<2000||y>2100||!m)throw Error("対象の年・月を確認してください。");const result=await extractPdf(doc,y,m);const filled:Record<string,LunchDay>={};for(const date of monthDays(month))filled[date]=result.days[date]??blank(date);for(const d of Object.values(filled))d.dishes=d.dishes.map(x=>({...x,image:images[normalized(x.name)]}));setDays(filled);setWarnings(result.warnings);setSelected(Object.keys(result.days)[0]??`${month}-01`);setStage("review");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function manual(){const filled:Record<string,LunchDay>={};monthDays(month).forEach(date=>filled[date]=blank(date));setDays(filled);setSelected(`${month}-01`);setStage("review");setWarnings(["原本を見ながら献立を入力してください。入力しない日は未登録のままです。"]);}
 function confirmAll(){setError("");for(const d of Object.values(days)){if(d.status==="meal"&&(!d.dishes.length||d.dishes.some(x=>!x.name.trim())||d.milk===null)){setSelected(d.date);setError(`${dayLabel(d.date)}の料理名・牛乳を確認してください。`);return;}}setDays(ds=>Object.fromEntries(Object.entries(ds).map(([k,d])=>[k,{...d,confirmed:d.status!=="unknown"}])));}
 const count=Object.values(days).filter(d=>d.status==="meal").length;const pending=Object.values(days).filter(d=>d.status!=="unknown"&&!d.confirmed).length;
 const changed=data.months[month]?monthDays(month).filter(date=>JSON.stringify(data.months[month].days[date])!==JSON.stringify(days[date])).length:0;
 async function save(){setError("");if(pending){setError("献立と牛乳を原本と見比べ、確認済みにしてください。");return;}if(!Object.values(days).some(d=>d.confirmed)){setError("1日以上の献立、または給食なしの日を登録してください。");return;}setBusy(true);const original=data.months[month];const previous=original?{key:original.key,name:original.name,pdf:original.pdf,days:original.days,importedAt:original.importedAt}:undefined;const monthData:LunchMonth={key:month,name:file?.name??existing?.name??"手入力",pdf:pdfURL,days,importedAt:new Date().toISOString(),previous};const success=await onSave(monthData,images);setBusy(false);if(success)onClose();}
 async function attachPhoto(f:File,date:string,id:string){try{const image=await readPhoto(f);patchDish(date,id,{image});const name=days[date].dishes.find(d=>d.id===id)?.name;if(name)setImages(prev=>({...prev,[normalized(name)]:image}));}catch(e){setError((e as Error).message);}}
 return <><Dialog open={open} onOpenChange={b=>{if(!b&&!busy){if(stage==="file")onClose();else setCancelConfirm(true);}}}><DialogContent className="import-dialog"><div className="dialog-heading"><span className="section-eyebrow"><FileText size={17}/>おうちのひとへ</span><DialogTitle>{stage==="file"?"給食の献立を入れる":"読み取り内容を確認"}</DialogTitle><DialogDescription>{stage==="file"?"PDFを選ぶだけで、子どもの画面に自動で表示します。":"原本を見ながら、日ごとに編集できます。"}</DialogDescription></div>
 {error&&<p className="error-box" role="alert">{error}</p>}{busy&&<div className="loading-progress"><Progress value={65}/><span>準備しています…</span></div>}
 {stage==="file"?<div className="upload-setup"><input ref={fileInput} type="file" accept="application/pdf,.pdf" className="sr-only" aria-label="給食PDFを選ぶ" onChange={e=>{const f=e.target.files?.[0];if(f)void selectFile(f);e.target.value="";}}/><button className="upload-zone" disabled={busy} onClick={()=>fileInput.current?.click()}><span className="upload-round"><Upload size={30}/></span><strong>{file?.name??"献立PDFを選ぶ"}</strong><span>スマホの「ファイル」から選べます</span><small>PDF・10MBまで・5ページまで</small></button><details><summary>読み取れないとき・年月を指定する</summary><label className="field-label">対象の年・月<input type="month" value={month} min="2000-01" max="2100-12" onChange={e=>setMonth(e.target.value)} /></label><p className="helper">通常は年月も自動で読み取ります。読み取れないときだけ、ここで指定できます。</p><button className="primary-button full" onClick={()=>void parse()} disabled={!doc||busy||!month}>この年月で読み取る</button><button className="text-button" onClick={manual} disabled={!month||busy}>手入力で登録する</button></details><div className="info-box">文字を選択できる、今回の献立表と同じ形式に対応。写真・スキャン・違う形式は、原本を見ながら手入力できます。PDFはこの端末に保存されます。同じ月のPDFは自動更新され、設定から1回戻せます。</div></div>:<>
 <div className="review-toolbar"><div><strong>{month.replace("-","年")}月</strong><span className="helper">給食 {count}日・未確認 {pending}日</span></div><button className="secondary-button" disabled={!doc} onClick={()=>setViewPDF(!viewPDF)}><Search size={18}/>{viewPDF?"編集に戻る":"原本を見る"}</button></div>
 {warnings.map((w,i)=><p className="helper" key={i}>{w}</p>)}
 {viewPDF&&doc?<div className="pdf-section"><div className="pdf-controls"><button className="icon-button" disabled={page===1} onClick={()=>setPage(page-1)} aria-label="PDFの前のページ"><ChevronLeft/></button><span>{page} / {doc.numPages}</span><button className="icon-button" disabled={page===doc.numPages} onClick={()=>setPage(page+1)} aria-label="PDFの次のページ"><ChevronRight/></button><button className="secondary-button" onClick={()=>setZoom(z=>z===.65?1.3:.65)}>{zoom===.65?"拡大":"縮小"}</button></div><div className="pdf-scroll"><PdfCanvas doc={doc} pageNumber={page} zoom={zoom}/></div></div>:<>
 <div className="review-days" aria-label="編集する日">{monthDays(month).map(date=>{const d=days[date];return <button key={date} onClick={()=>setSelected(date)} className={`review-day ${selected===date?"selected":""} ${d?.confirmed?"reviewed":""}`} aria-label={`${dayLabel(date)} ${d?.status==="meal"?"給食あり":d?.status==="none"?"給食なし":"未登録"}`}><span>{Number(date.slice(8))}</span><small>{d?.confirmed?"確認済":d?.status==="meal"?"給食":d?.status==="none"?"休み":"—"}</small></button>;})}</div>
 {chosen&&<div className="day-editor"><h3>{dayLabel(selected)}</h3><details className="date-correction"><summary>日付を変更する</summary><label className="field-label">移動先の日付<input type="date" value={selected} min={`${month}-01`} max={monthDays(month).at(-1)} onChange={e=>{const target=e.target.value;if(!validDate(target)||!target.startsWith(month+"-"))return;if(days[target]?.status!=="unknown"){setError("移動先には献立があります。先に移動先を未登録にしてください。");return;}setDays(ds=>({...ds,[target]:{...ds[selected],date:target,confirmed:false},[selected]:blank(selected)}));setSelected(target);}}/></label></details><Choice value={chosen.status} label="給食の有無" options={[{value:"meal",label:"給食あり"},{value:"none",label:"給食なし"},{value:"unknown",label:"未登録にする"}]} onChange={v=>patchDay(selected,{status:v as LunchDay["status"],confirmed:false,milk:v==="meal"?chosen.milk:false})}/>
 {chosen.status==="meal"&&<><label className="field-label">牛乳<Choice value={chosen.milk===null?"unknown":String(chosen.milk)} label="牛乳" options={[{value:"unknown",label:"確認してください"},{value:"true",label:"牛乳あり"},{value:"false",label:"牛乳なし"}]} onChange={v=>patchDay(selected,{milk:v==="unknown"?null:v==="true",confirmed:false})}/></label>{chosen.dishes.map((dish,index)=><div className="dish-editor" key={dish.id}><div className="dish-editor-head"><button className="art-button" aria-label={`${dish.name||"料理"}のイラストを選ぶ`} onClick={()=>{setArtPick({date:selected,dish:dish.id});setQuery("");}}><FoodImage name={dish.name} art={dish.art} image={dish.image}/><span>絵を選ぶ</span></button><div className="dish-fields"><label>料理名<input value={dish.name} maxLength={120} onChange={e=>patchDish(selected,dish.id,{name:e.target.value,reading:kana(e.target.value),art:findArt(e.target.value),image:images[normalized(e.target.value)]})}/></label><label>よみがな<input value={dish.reading} maxLength={160} onChange={e=>patchDish(selected,dish.id,{reading:e.target.value})}/></label></div></div><div className="dish-editor-actions"><label className="text-button photo-input"><ImagePlus size={17}/>写真を入れる<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void attachPhoto(f,selected,dish.id);e.target.value="";}}/></label><button className="icon-button" aria-label="料理を上へ" disabled={index===0} onClick={()=>{const ds=[...chosen.dishes];[ds[index-1],ds[index]]=[ds[index],ds[index-1]];patchDay(selected,{dishes:ds,confirmed:false});}}><ArrowUp size={18}/></button><button className="icon-button" aria-label="料理を下へ" disabled={index===chosen.dishes.length-1} onClick={()=>{const ds=[...chosen.dishes];[ds[index+1],ds[index]]=[ds[index],ds[index+1]];patchDay(selected,{dishes:ds,confirmed:false});}}><ArrowDown size={18}/></button><button className="icon-button" aria-label="料理を削除" onClick={()=>patchDay(selected,{dishes:chosen.dishes.filter(x=>x.id!==dish.id),confirmed:false})}><Trash2 size={18}/></button></div></div>)}<button className="secondary-button full" onClick={()=>patchDay(selected,{dishes:[...chosen.dishes,{id:crypto.randomUUID(),name:"",reading:""}],confirmed:false})}><Plus size={18}/>料理を追加</button></>}
 {chosen.status!=="unknown"&&<><label className="field-label">行事・お知らせ<input value={chosen.event} maxLength={300} placeholder="お月見メニュー など" onChange={e=>patchDay(selected,{event:e.target.value,confirmed:false})}/></label><Check checked={chosen.confirmed} onChange={b=>{if(b&&chosen.status==="meal"&&(!chosen.dishes.length||chosen.dishes.some(d=>!d.name.trim())||chosen.milk===null)){setError("料理名と牛乳を入力してください。");return;}setError("");patchDay(selected,{confirmed:b});}}>この日の内容を確認しました</Check></>}
 </div>}
 <details className="batch-actions"><summary>まとめて確認する</summary><p className="helper">原本と全日を見比べたあとに使ってください。</p><button className="secondary-button full" onClick={confirmAll}><CheckCircle2 size={18}/>入力した日をすべて確認済みにする</button><button className="text-button" onClick={()=>setDays(ds=>Object.fromEntries(Object.entries(ds).map(([k,d])=>{const w=dateObj(k).getUTCDay();return[k,(w===0||w===6)&&d.status==="unknown"?{...d,status:"none",milk:false,event:"おやすみ",confirmed:true}:d];})))}>未登録の土日を「給食なし」にする</button></details>
 </>}
 {data.months[month]&&<div className="info-box">登録済みの{month}を更新します。変更対象 {changed}日。前の内容は1回分残ります。</div>}
 <div className="import-footer"><span className="helper">未登録の日は、勝手に補いません。</span><button className="primary-button full" disabled={busy||pending>0} onClick={()=>data.months[month]?setConfirm(true):void save()}><CheckCircle2 size={20}/>{count}日分の給食を保存</button></div>
 </>}
 </DialogContent></Dialog>
 <Dialog open={!!artPick} onOpenChange={b=>{if(!b)setArtPick(null);}}><DialogContent className="art-dialog"><DialogTitle>料理のイラストを選ぶ</DialogTitle><DialogDescription>料理に合う絵を選んでください。</DialogDescription><input placeholder="料理名で探す" value={query} onChange={e=>setQuery(e.target.value)} aria-label="イラストを探す"/><div className="art-grid">{foodCatalog.filter(x=>normalized(kana(x.name)).includes(normalized(kana(query)))).map(x=><button key={x.art} onClick={()=>{if(artPick)patchDish(artPick.date,artPick.dish,{art:x.art,image:undefined});setArtPick(null);}}><FoodImage art={x.art} name={x.name}/><span>{x.name}</span></button>)}</div></DialogContent></Dialog>
 <Confirm open={confirm} onOpenChange={setConfirm} title="この月の献立を更新しますか？" description={`${month}の${changed}日が変更対象です。他の月はそのまま残ります。前の内容には1回戻せます。`} action="更新して保存" onConfirm={()=>void save()}/>
 <Confirm open={cancelConfirm} onOpenChange={setCancelConfirm} title="編集を閉じますか？" description="この画面で変更した内容は保存されません。登録済みの献立はそのまま残ります。" action="保存せず閉じる" onConfirm={onClose}/>
 </>;
}
