"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Calendar} from "@/components/ui/calendar";
import {Empty} from "@/components/ui/empty";
import {Skeleton} from "@/components/ui/skeleton";
import {Toaster} from "@/components/ui/sonner";
import {ja} from "date-fns/locale";
import {toast} from "sonner";
import {Sun,Moon,ChevronLeft,ChevronRight,CalendarDays,Utensils,Settings,Upload,Milk,Sparkles,Home,LockKeyhole,CheckCircle2,WifiOff} from "lucide-react";
import type {AppData,LunchMonth} from "@/lib/types";
import {emptyData,readData,writeData} from "@/lib/storage";
import {todayJapan,shiftDay,dayLabel,validDate} from "@/lib/dates";
import {rankDinners,allowedDinners} from "@/lib/dinners";
import {FoodImage} from "./food-image";
import ParentPanel,{type SaveData} from "./parent-panel";
import LunchImport from "./lunch-import";
import DinnerView from "./dinner-view";
interface WebContext {registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>}
export default function MealApp(){
 const[tab,setTab]=useState("lunch");const[data,setData]=useState<AppData|null>(null);const[loadError,setLoadError]=useState("");const[today,setToday]=useState("");const[date,setDate]=useState("");const[todayMode,setTodayMode]=useState(true);const[calendar,setCalendar]=useState(false);const[calendarMonth,setCalendarMonth]=useState<Date>();const[parent,setParent]=useState(false);const[gate,setGate]=useState(false);const[pressing,setPressing]=useState(false);const[importing,setImporting]=useState(false);const[editing,setEditing]=useState<LunchMonth|undefined>();const[offline,setOffline]=useState("オフラインの準備中…");const[online,setOnline]=useState(true);const ref=useRef<AppData|null>(null);const queue=useRef(Promise.resolve());const hold=useRef<ReturnType<typeof setTimeout>|null>(null);const dateMode=useRef(true);const mounted=useRef(false);const autoSaving=useRef(false);
 const save:SaveData=useCallback((fn)=>{let resolve:(b:boolean)=>void=()=>{};const result=new Promise<boolean>(r=>resolve=r);queue.current=queue.current.then(async()=>{try{const current=ref.current;if(!current)throw Error("保存の準備ができていません。");const next=fn(current);if(next===current){resolve(true);return;}const saved=await writeData(next,current.revision);ref.current=saved;setData(saved);resolve(true);}catch(e){toast.error((e as Error).message);resolve(false);}});return result;},[]);
 useEffect(()=>{mounted.current=true;const now=todayJapan();setToday(now);setDate(now);setOnline(navigator.onLine);void readData().then(d=>{if(!mounted.current)return;ref.current=d;setData(d);}).catch(e=>setLoadError((e as Error).message));const update=()=>{const current=todayJapan();setToday(current);if(dateMode.current)setDate(current);};const resume=()=>{if(document.visibilityState==="visible"){dateMode.current=true;setTodayMode(true);setDate(todayJapan());setToday(todayJapan());}};const offlineChange=()=>setOnline(navigator.onLine);document.addEventListener("visibilitychange",resume);window.addEventListener("online",offlineChange);window.addEventListener("offline",offlineChange);const timer=setInterval(update,30000);return()=>{mounted.current=false;clearInterval(timer);document.removeEventListener("visibilitychange",resume);window.removeEventListener("online",offlineChange);window.removeEventListener("offline",offlineChange);};},[]);
 useEffect(()=>{if(!("serviceWorker"in navigator)){setOffline("このブラウザはオフライン保存に対応していません。");return;}if(location.hostname==="terminal.local"){setOffline("オフライン機能は公開後のアプリで利用できます。");return;}const onMessage=(e:MessageEvent)=>{if(e.data?.type==="OFFLINE_READY")setOffline("オフライン準備完了。登録した献立と料理画像を電波がなくても表示できます。");if(e.data?.type==="OFFLINE_FAILED")setOffline("一部の画像をまだ保存できていません。通信できる場所で開き直してください。");};navigator.serviceWorker.addEventListener("message",onMessage);void navigator.serviceWorker.register("/sw.js",{scope:"/"}).then(()=>navigator.serviceWorker.ready).then(reg=>{reg.active?.postMessage({type:"PREPARE_OFFLINE"});void navigator.storage?.persist?.();}).catch(()=>setOffline("オフライン保存ができませんでした。通常のブラウザで開いてください。"));return()=>navigator.serviceWorker.removeEventListener("message",onMessage);},[]);
 useEffect(()=>{if(!data||!today||autoSaving.current)return;const selected=data.suggestions[today];const pool=rankDinners(data,today);if(!pool.length||selected&&pool.some(x=>x.id===selected.id))return;autoSaving.current=true;void save(d=>{const ranked=rankDinners(d,today);const candidate=ranked.find(x=>x.id===d.dinner[today])??ranked[0];if(!candidate)return d;return{...d,suggestions:{...d.suggestions,[today]:{id:candidate.id,seen:[candidate.id],trail:[]}}};}).finally(()=>autoSaving.current=false);},[data,today,save]);
 const navigate=useCallback((value:string)=>{if(!validDate(value))return;setDate(value);const isToday=value===todayJapan();dateMode.current=isToday;setTodayMode(isToday);},[]);
 const viewRef=useRef({date,tab,data});viewRef.current={date,tab,data};
 useEffect(()=>{const context=(document as Document&{modelContext?:WebContext}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();const tools=[{name:"read_displayed_meals",title:"表示中の献立を読む",description:"表示中の日付の給食と、今日の夕食候補・決定済みメニューを読む。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>{const v=viewRef.current;return{date:v.date,lunch:v.data?.months[v.date.slice(0,7)]?.days[v.date]??null,dinnerCandidate:v.data?.suggestions[todayJapan()]?.id??null,decidedDinner:v.data?.dinner[todayJapan()]??null};}},{name:"show_lunch_date",title:"指定日の給食を表示",description:"YYYY-MM-DDの給食を表示する。登録データは変更しない。",inputSchema:{type:"object",properties:{date:{type:"string",description:"YYYY-MM-DD"}},required:["date"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const v=input as {date?:string};if(!v||typeof v.date!=="string"||!validDate(v.date))throw Error("有効なYYYY-MM-DDの日付を指定してください。");navigate(v.date);setTab("lunch");await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return{date:v.date,status:viewRef.current.data?.months[v.date.slice(0,7)]?.days[v.date]?.status??"unknown"};}}];for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[navigate]);
 function stopHold(){if(hold.current)clearTimeout(hold.current);hold.current=null;setPressing(false);}
 function startHold(){stopHold();setPressing(true);hold.current=setTimeout(()=>{setParent(true);setGate(false);setPressing(false);hold.current=null;},3000);}
 function beginImport(m?:LunchMonth){setEditing(m);setParent(false);setImporting(true);}
 async function saveMonth(m:LunchMonth,images:Record<string,string>){const days=Object.fromEntries(Object.entries(m.days).map(([k,d])=>[k,d.status==="meal"?d:{...d,dishes:[],milk:false}]));const ok=await save(d=>({...d,images,months:{...d.months,[m.key]:{...m,days}}}));if(ok){toast.success(`${m.key.replace("-","年")}月の献立を保存しました`);navigate(Object.values(days).find(d=>d.status==="meal")?.date??`${m.key}-01`);}return ok;}
 const current=data?.months[date.slice(0,7)]?.days[date];const hasAny=!!data&&Object.keys(data.months).length>0;
 return <><Tabs value={tab} onValueChange={setTab} className="meal-app"><header className="app-header"><a href="/" className="brand"><span className="brand-symbol"><Utensils size={22}/></span>きょうのごはん<span className="brand-dot">.</span></a><button className={`parent-link ${pressing?"holding":""}`} onPointerDown={startHold} onPointerUp={stopHold} onPointerLeave={stopHold} onPointerCancel={stopHold} onContextMenu={e=>e.preventDefault()} onClick={()=>{if(!parent)setGate(true);}} aria-label="おうちのひと。3秒長押しで開きます"><Settings size={17}/><span>おうちのひと</span></button></header><main className="app-main">{!online&&<div className="offline-badge"><WifiOff size={14}/>オフライン</div>}{loadError?<Empty className="empty-state"><h2>データを開けませんでした</h2><p>{loadError}</p><button className="secondary-button" onClick={()=>location.reload()}>もう一度ひらく</button></Empty>:!data||!date?<div aria-label="献立を読み込み中" className="loading-surface"><Skeleton className="h-14 w-3/4 rounded-xl"/><Skeleton className="h-64 w-full rounded-3xl"/></div>:<>
 <TabsContent value="lunch"><div className="section-eyebrow"><Sun size={18}/>おひるの おたのしみ</div><div className="title-row"><h1>{todayMode?"きょうの":"このひの"} きゅうしょく</h1><span className="tiny-label">LUNCH TIME</span></div><div className="date-bar"><button aria-label="前の日" className="icon-button" onClick={()=>navigate(shiftDay(date,-1))}><ChevronLeft/></button><button className="date-picker" onClick={()=>{setCalendarMonth(new Date(date+"T12:00:00"));setCalendar(true);}}><CalendarDays size={20}/>{dayLabel(date)}<ChevronDownSmall/></button><button aria-label="次の日" className="icon-button" onClick={()=>navigate(shiftDay(date,1))}><ChevronRight/></button></div>{!todayMode&&<button className="today-return" onClick={()=>navigate(today)}><Sun size={15}/>きょうに もどる</button>}
 {current?.status==="meal"&&current.confirmed?<><div className="meal-intro"><h2>{todayMode?"きょうは":"このひは"} なにかな？</h2>{current.event&&<span className="event-tag"><Sparkles size={15}/>{current.event}</span>}</div><div className="lunch-tray" aria-live="polite"><div className={`dish-grid dishes-${current.dishes.length}`}>{current.dishes.map((dish,i)=><article className="dish-card" key={dish.id}><span className="dish-number">{String(i+1).padStart(2,"0")}</span><FoodImage name={dish.name} art={dish.art} image={dish.image}/><h3>{dish.reading||dish.name}</h3>{dish.reading&&dish.reading!==dish.name&&<p>{dish.name}</p>}</article>)}</div>{current.milk&&<div className="milk-strip"><FoodImage art={56} name="ぎゅうにゅう"/><div><span>いっしょに のもう</span><strong>ぎゅうにゅう</strong></div><Milk size={24}/></div>}</div><p className="meal-footer"><Utensils size={17}/>たのしく、おいしく。いただきます！</p><p className="illustration-note">イラストは料理のイメージです。</p></>:current?.status==="none"&&current.confirmed?<Empty className="empty-state rest-state"><div className="empty-icon"><Home size={42}/></div><h2>きょうの きゅうしょくは<br/>おやすみだよ</h2>{current.event&&<p>{current.event}</p>}<button className="secondary-button" onClick={()=>setTab("dinner")}><Moon size={19}/>ゆうごはんを みる</button></Empty>:<Empty className="empty-state"><div className="empty-food-row" aria-hidden="true"><FoodImage art={6} name="ごはん"/><FoodImage art={54} name="グラタン"/><FoodImage art={2} name="スープ"/></div><h2>{hasAny?"このひの こんだては\nまだ はいっていないよ":"きゅうしょく、なにかな？"}</h2><p>おうちのひとと<br/>こんだてひょうを いれてみよう。</p><button className="primary-button" onClick={()=>hasAny?setGate(true):beginImport()}><Upload size={20}/>献立PDFを入れる</button><span className="helper">{date.slice(0,7).replace("-","年")}月の献立</span></Empty>}
 </TabsContent><TabsContent value="dinner"><DinnerView data={data} today={today} save={save} onSettings={()=>setGate(true)}/></TabsContent>
 </>}</main><nav className="bottom-nav" aria-label="ごはんを選ぶ"><TabsList><TabsTrigger value="lunch"><Sun/>きゅうしょく</TabsTrigger><TabsTrigger value="dinner"><Moon/>ゆうごはん</TabsTrigger></TabsList></nav></Tabs>
 <Dialog open={calendar} onOpenChange={setCalendar}><DialogContent className="calendar-dialog"><DialogTitle>ひづけを えらぼう</DialogTitle><DialogDescription>みたい日の こんだてが でるよ。</DialogDescription><label className="field-label">年月<input type="month" aria-label="カレンダーの年月" value={calendarMonth?`${calendarMonth.getFullYear()}-${String(calendarMonth.getMonth()+1).padStart(2,"0")}`:""} onChange={e=>{if(e.target.value)setCalendarMonth(new Date(e.target.value+"-01T12:00:00"));}}/></label><Calendar mode="single" locale={ja} weekStartsOn={1} month={calendarMonth} onMonthChange={setCalendarMonth} selected={date?new Date(date+"T12:00:00"):undefined} onSelect={d=>{if(d){navigate(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`);setCalendar(false);}}} className="meal-calendar"/><button className="secondary-button full" onClick={()=>{navigate(today);setCalendar(false);}}>きょう</button></DialogContent></Dialog>
 <Dialog open={gate} onOpenChange={b=>{setGate(b);stopHold();}}><DialogContent className="gate-dialog"><DialogTitle>おうちのひとへ</DialogTitle><DialogDescription>まちがって変更しないように、ボタンを3秒長押ししてください。キーボードでは Enter で開けます。</DialogDescription><button className={`primary-button full hold-button ${pressing?"holding":""}`} onPointerDown={startHold} onPointerUp={stopHold} onPointerLeave={stopHold} onPointerCancel={stopHold} onContextMenu={e=>e.preventDefault()} onKeyDown={e=>{if((e.key===" "||e.key==="Enter")&&!e.repeat){e.preventDefault();setGate(false);setParent(true);stopHold();}}} onKeyUp={stopHold}><LockKeyhole size={20}/>{pressing?"そのまま おしてね…":"3秒長押しで開く"}</button></DialogContent></Dialog>
 {data&&<ParentPanel key={parent?"open":"closed"} open={parent} onOpenChange={setParent} data={data} today={today} save={save} onImport={()=>beginImport()} onEdit={beginImport} offline={offline}/>}{data&&importing&&<LunchImport open={importing} onClose={()=>setImporting(false)} data={data} onSave={saveMonth} existing={editing}/>}
 <Toaster position="top-center" theme="light" richColors closeButton/>
 </>;
}
function ChevronDownSmall(){return <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>;}
