"use client";
import {useRef,useState} from "react";
import {Sheet,SheetContent,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Upload,Download,RotateCcw,FileText,Plus,Heart,Smartphone,Leaf} from "lucide-react";
import {toast} from "sonner";
import {Choice,Confirm} from "./controls";
import {dinners,dinnerById,allowedDinners} from "@/lib/dinners";
import {dayLabel,weekDates} from "@/lib/dates";
import {downloadJSON,readBackup} from "@/lib/storage";
import type {AppData,LunchMonth} from "@/lib/types";
export type SaveData=(fn:(data:AppData)=>AppData)=>Promise<boolean>;
export default function ParentPanel({open,onOpenChange,data,today,save,onImport,onEdit,offline}:{open:boolean;onOpenChange:(open:boolean)=>void;data:AppData;today:string;save:SaveData;onImport:()=>void;onEdit:(m:LunchMonth)=>void;offline:string}){
 const[dislikes,setDislikes]=useState(data.dislikes.join("、"));const[restore,setRestore]=useState<AppData|null>(null);const[undo,setUndo]=useState<string|null>(null);const restoreInput=useRef<HTMLInputElement>(null);
 async function history(day:string,id:string){const okay=await save(d=>{if(id!=="none"){const testId=id==="manual-curry"?"curry":id;if(!allowedDinners({...d,dislikes:[]},day).some(m=>m.id===testId))throw Error("この週はカレー・シチューを選んだ日があります。先にその日を変更してください。");}const dinner={...d.dinner};if(id==="none")delete dinner[day];else dinner[day]=id;return{...d,dinner};});if(okay)toast.success("夕食の記録を更新しました");}
 return <><Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="parent-panel"><div className="dialog-heading"><span className="section-eyebrow">SETTINGS</span><SheetTitle>おうちのひとへ</SheetTitle><SheetDescription>献立の登録と、家族の設定。</SheetDescription></div><section className="settings-section"><h3><FileText size={19}/>給食の献立</h3><button className="primary-button full" onClick={onImport}><Upload size={19}/>献立PDFをアップロード</button><div className="month-list">{Object.values(data.months).sort((a,b)=>b.key.localeCompare(a.key)).map(m=><div key={m.key} className="month-item"><div><strong>{m.key.replace("-","年")}月</strong><span>{Object.values(m.days).filter(d=>d.status==="meal").length}日分の給食</span></div><button className="text-button" onClick={()=>onEdit(m)}>確認・編集</button>{m.previous&&<button className="icon-button" aria-label={`${m.key}を前の内容に戻す`} onClick={()=>setUndo(m.key)}><RotateCcw size={18}/></button>}</div>)}</div><p className="helper">PDFはスマホの中で読み取ります。登録データはこのブラウザだけに保存されます。</p></section>
 <section className="settings-section"><h3><Leaf size={19}/>使わない食材</h3><label className="field-label">食材名を「、」で区切る<input placeholder="例：牛肉、トマト" value={dislikes} maxLength={300} onChange={e=>setDislikes(e.target.value)}/></label><p className="helper">材料名に含まれる文字で除外します（例：「牛」で牛こま肉・牛乳）。市販のタレやルウの原材料は商品表示を確認してください。</p><button className="secondary-button full" onClick={async()=>{if(await save(d=>({...d,dislikes:dislikes.split(/[、,\n]/).map(s=>s.trim()).filter(Boolean)})))toast.success("食材の設定を保存しました");}}>食材の設定を保存</button></section>
 <section className="settings-section"><h3>今週の夕食</h3><p className="helper">カレーとシチューは合わせて週1回。月曜日に切り替わります。アプリを使う前の分もここで記録できます。</p>{weekDates(today).map(day=><div className="history-row" key={day}><label>{dayLabel(day)}{day===today&&<small>今日</small>}</label><Choice label={`${dayLabel(day)}の夕食`} value={data.dinner[day]??"none"} onChange={id=>void history(day,id)} options={[{value:"none",label:"まだ決めていない"},...dinners.map(m=>({value:m.id,label:m.main})),{value:"manual-curry",label:"別のカレー・シチューを食べた"}]}/></div>)}</section>
 <section className="settings-section"><h3><Heart size={19}/>お気に入り</h3><p className="helper">「お気に入り」を付けたメニューを少し優先して提案します。</p><div className="favorite-list">{data.favorites.length?data.favorites.map(id=><span className="tag" key={id}>{dinnerById(id)?.main}</span>):<span className="helper">夕食のハートから登録できます。</span>}</div></section>
 <section className="settings-section"><h3><Download size={19}/>バックアップ</h3><p className="helper">機種変更やブラウザのデータ削除に備えて、献立・原本PDF・写真をひとつのファイルに保存できます。</p><button className="secondary-button full" onClick={()=>downloadJSON(data)}><Download size={18}/>バックアップを保存</button><input ref={restoreInput} type="file" accept="application/json,.json" className="sr-only" aria-label="バックアップファイル" onChange={async e=>{const f=e.target.files?.[0];e.target.value="";if(!f)return;try{setRestore(await readBackup(f));}catch(err){toast.error((err as Error).message);}}}/><button className="text-button" onClick={()=>restoreInput.current?.click()}><RotateCcw size={16}/>バックアップから復元</button></section>
 <section className="settings-section"><h3><Smartphone size={19}/>ホーム画面で使う</h3><p>AndroidはChromeのメニューから「ホーム画面に追加」。iPhoneはSafariの共有から「ホーム画面に追加」で使えます。</p><p className="helper offline-info">{offline}</p><p className="helper">日付は日本時間です。調理時間は目安で、炊いたごはんを使います。ホットクックは機種未設定のため使いません。</p></section>
 </SheetContent></Sheet>
 <Confirm open={!!restore} onOpenChange={b=>{if(!b)setRestore(null);}} title="バックアップから復元しますか？" description={`給食 ${restore?Object.keys(restore.months).length:0}か月分と夕食の記録で、この端末のデータを置き換えます。必要なら先に現在のバックアップを保存してください。`} action="復元する" onConfirm={async()=>{if(restore&&await save(d=>({...restore,revision:d.revision})))toast.success("バックアップから復元しました");setRestore(null);}}/>
 <Confirm open={!!undo} onOpenChange={b=>{if(!b)setUndo(null);}} title="前の献立に戻しますか？" description={`${undo}の給食を、前回保存した内容に戻します。現在の内容も1回分残ります。`} action="前の内容に戻す" onConfirm={async()=>{if(undo){await save(d=>{const m=d.months[undo];if(!m?.previous)return d;const {previous,...current}=m;return{...d,months:{...d.months,[undo]:{...previous,previous:current}}};});toast.success("前の献立に戻しました");}setUndo(null);}}/>
 </>;
}
