import type { AppData, Dinner, Ingredient, DinnerSelection } from "./types";
import { weekStart, shiftDay } from "./dates";
const veg=(name:string,amount:string):Ingredient=>({name,amount,category:"野菜"});
const meat=(name:string,amount:string):Ingredient=>({name,amount,category:"肉"});
const other=(name:string,amount:string):Ingredient=>({name,amount,category:"その他"});
const rice=other("炊いたごはん・冷凍ごはん","700〜800g");
export const dinners:Dinner[]=[
{id:"beef",category:"牛こま焼き",title:"牛こま焼肉と切るだけ野菜",main:"牛こまの焼肉だれ焼き",side:"きゅうりとトマト",reading:"ぎゅうにくの やきにく",time:15,image:"/food/dinner-beef.webp",weeklyLimited:false,ingredients:[meat("牛こま肉","500g"),veg("きゅうり","2本"),veg("トマト","2個"),other("焼肉のタレ","大さじ4"),other("油","小さじ1"),rice],steps:["きゅうりとトマトを食べやすく切り、別のお皿に盛る。ごはんを温める。","フライパンに油を熱し、牛肉を広げて中心まで焼く。大きさに合わせて2回に分ける。","焼肉のタレをからめる。お肉・野菜・ごはんをそれぞれ盛りつける。"],stepLabels:["野菜を切る","お肉を焼く","タレをからめる"]},
{id:"shabu",category:"しゃぶしゃぶ",title:"やわらか豚しゃぶと温野菜",main:"豚しゃぶのしょうゆだれ",side:"蒸しキャベツ・にんじんときゅうり",reading:"ぶたしゃぶ",time:20,image:"/food/dinner-shabu.webp",weeklyLimited:false,ingredients:[meat("豚しゃぶしゃぶ用肉","500g"),veg("キャベツ","1/4個（250g）"),veg("にんじん","1本（150g）"),veg("きゅうり","1本"),other("しょうゆ","大さじ2"),other("カンタン酢","大さじ2"),rice],steps:["キャベツをざく切り、にんじんを薄切りにする。耐熱容器に入れ水大さじ2を加え、ふんわりラップで600W約5分。きゅうりは切る。","鍋に湯を沸かし、豚肉を少しずつ入れる。重なりをほどいて中心までしっかりゆで、取り出す。","しょうゆとカンタン酢を混ぜる。温めたごはん、お肉、野菜を別々に盛り、たれは添える。"],stepLabels:["野菜をレンジへ","お肉をゆでる","たれを添える"]},
{id:"chicken",category:"蒸し鶏",title:"蒸し鶏とやさしい根菜",main:"鶏むねの塩蒸し",side:"蒸しにんじん・大根・ブロッコリー",reading:"むしどり",time:20,image:"/food/dinner-chicken.webp",weeklyLimited:false,ingredients:[meat("鶏むね肉","600g"),veg("にんじん","1本（150g）"),veg("大根","200g"),veg("ブロッコリー","150g"),other("塩","小さじ1/2"),other("しょうゆ","大さじ1（お好みで）"),rice],steps:["鶏むね肉は厚さ1cmのそぎ切りにして塩をふる。にんじん・大根は薄切り、ブロッコリーは小房にする。","野菜を水大さじ2と耐熱容器に入れラップをし、600W約6分。並行して鶏肉をフライパンに重ねず並べ、水100mlを加えふたをする。","鶏肉を中火で約8分蒸し、中心まで火が通ったことを確認する。足りなければ追加加熱。温めたごはんと野菜を別に盛り、しょうゆを添える。"],stepLabels:["薄く切る","野菜をレンジへ","鶏肉を蒸す"]},
{id:"pork",category:"ポークステーキ",title:"ポークステーキのバターしょうゆ",main:"薄切りポークステーキ",side:"レンチンブロッコリーとトマト",reading:"ぽーくすてーき",time:20,image:"/food/dinner-pork.webp",weeklyLimited:false,ingredients:[meat("豚ロース肉（厚さ1cm程度）","4枚（約500g）"),veg("ブロッコリー","1株（250g）"),veg("トマト","2個"),other("しょうゆ","大さじ1と1/2"),other("バター","15g"),other("塩","少々"),other("油","小さじ1"),rice],steps:["ブロッコリーを小房にして水大さじ2と600W約4分加熱。トマトを切る。豚肉の筋を切り、塩をふる。","フライパンに油を熱し、豚肉を両面焼く。ふたをして中まで火を通す。重ならなければ4枚一緒に、難しければ2回に分ける。","バターとしょうゆを加えてからめる。食べやすく切り、野菜は別皿に。温めたごはんを添える。"],stepLabels:["野菜を用意","お肉を焼く","バターしょうゆ"]},
{id:"nikujaga",category:"肉じゃが",title:"小さめじゃがいもの肉じゃが",main:"フライパン肉じゃが",side:"きゅうりのカンタン酢漬け",reading:"にくじゃが",time:20,image:"/food/dinner-nikujaga.webp",weeklyLimited:false,ingredients:[meat("牛こま肉","400g"),veg("じゃがいも","3個（350g）"),veg("にんじん","1本（150g）"),veg("玉ねぎ","1個"),veg("きゅうり","2本"),other("しょうゆ","大さじ3"),other("砂糖","大さじ1と1/2"),other("カンタン酢","大さじ3"),other("油","小さじ1"),rice],steps:["じゃがいもは1.5cm角、にんじんは薄切り。水大さじ2と耐熱容器で600W約6分加熱。並行してきゅうりを薄切りにしカンタン酢に漬ける。","玉ねぎを薄切りにする。油を熱したフライパンで牛肉と玉ねぎを炒める。根菜、しょうゆ、砂糖、水150mlを加える。","ふたをして約7分煮る。根菜がやわらかく、お肉に火が通ったら完成。きゅうりは別皿にし、温めたごはんを添える。"],stepLabels:["根菜をレンジへ","お肉を焼く","いっしょに煮る"]},
{id:"tomato",category:"トマト煮",title:"鶏肉のシンプルトマト煮",main:"鶏肉のトマト煮",side:"レタスときゅうりのサラダ",reading:"とりにくの とまとに",time:20,image:"/food/dinner-tomato.webp",weeklyLimited:false,ingredients:[meat("鶏もも肉（小さめカット）","600g"),veg("レタス","1/2個"),veg("きゅうり","1本"),other("カットトマト缶","1缶（400g）"),other("塩","小さじ1/2（味を見て調整）"),other("しょうゆ","小さじ2"),other("油","小さじ2"),rice],steps:["鶏肉を2cm程度に整える。レタスはちぎり、きゅうりは切る。野菜は洗って水気を切り別皿に盛る。","油を熱したフライパンで鶏肉を約5分焼く。トマト缶、塩、しょうゆを入れる。","ふたをして約8分煮て、鶏肉の中心まで火を通す。足りなければ追加加熱。温めたごはんを添える。"],stepLabels:["切る・ちぎる","鶏肉を焼く","トマトで煮る"]},
{id:"curry",category:"カレー・シチュー",title:"小さめ野菜の甘口カレー",main:"牛こまの甘口カレー",side:"トマトときゅうり",reading:"あまくち かれー",time:20,image:"/food/dinner-curry.webp",weeklyLimited:true,ingredients:[meat("牛こま肉","350g"),veg("じゃがいも","2個（250g）"),veg("にんじん","1本（150g）"),veg("玉ねぎ","1個"),veg("トマト","1個"),veg("きゅうり","1本"),other("甘口カレールウ","4皿分（箱の表示量）"),other("油","小さじ1"),rice],steps:["じゃがいもを1cm角、にんじんを薄切りにし、水大さじ2と600W約6分加熱。並行して玉ねぎを薄切り、副菜の野菜を切る。","油を熱した鍋で牛肉と玉ねぎを炒める。根菜とルウの箱に書かれた4皿分の水を加え、ふたをして約5分煮る。","火を止めルウを溶かし、弱火で約5分。野菜のやわらかさと肉の火通りを確認する。温めたごはんと盛り、副菜は別皿に。"],stepLabels:["野菜を小さく","お肉と煮る","ルウを溶かす"]},
{id:"stew",category:"カレー・シチュー",title:"鶏肉のやさしいクリームシチュー",main:"小さめ野菜のチキンシチュー",side:"レンチンブロッコリー",reading:"くりーむ しちゅー",time:20,image:"/food/dinner-stew.webp",weeklyLimited:true,ingredients:[meat("鶏もも肉（小さめカット）","500g"),veg("じゃがいも","2個（250g）"),veg("にんじん","1本（150g）"),veg("玉ねぎ","1個"),veg("ブロッコリー","1株（250g）"),other("クリームシチュールウ","4皿分（箱の表示量）"),other("牛乳","箱の表示量（目安200ml）"),other("油","小さじ1"),rice],steps:["じゃがいもは1cm角、にんじん・玉ねぎは薄切りにする。根菜を水大さじ2と600W約6分加熱。並行して油で鶏肉と玉ねぎを約5分焼く。","鍋に根菜と箱の表示どおりの水を入れ、ふたをして約5分煮る。並行して小房にしたブロッコリーを水大さじ2と600W約4分加熱。","火を止めルウを溶かし、牛乳を加えて約5分弱火で煮る。鶏肉の中心まで火が通ったか確認。温めたごはんと、別皿のブロッコリーを添える。"],stepLabels:["小さく切る","鶏肉と煮る","ルウ・牛乳を入れる"]},
{"id": "web-mapo", "category": "簡単定番", "title": "辛くない麻婆豆腐と切るだけ野菜", "main": "甘口だれの麻婆豆腐", "reading": "からくない まーぼーどうふ", "side": "きゅうりとトマト", "time": 20, "image": "/food/dinner-mapo.webp", "weeklyLimited": false, "source": {"name": "キッコーマン「お子さま麻婆豆腐」", "url": "https://www.kikkoman.co.jp/homecook/search/recipe/00007368/"}, "ingredients": [{"name": "豚ひき肉", "amount": "200g", "category": "肉"}, {"name": "ねぎ", "amount": "1/2本", "category": "野菜"}, {"name": "きゅうり", "amount": "2本", "category": "野菜"}, {"name": "トマト", "amount": "2個", "category": "野菜"}, {"name": "絹ごし豆腐", "amount": "400g", "category": "その他"}, {"name": "甘口の焼肉のタレ", "amount": "大さじ3", "category": "その他"}, {"name": "しょうゆ", "amount": "大さじ1", "category": "その他"}, {"name": "酢", "amount": "小さじ1/2", "category": "その他"}, {"name": "片栗粉", "amount": "小さじ2（水小さじ4で溶く）", "category": "その他"}, {"name": "油", "amount": "大さじ1", "category": "その他"}, {"name": "炊いたごはん・冷凍ごはん", "amount": "700〜800g", "category": "その他"}], "stepLabels": ["豆腐・野菜を切る", "ひき肉を炒める", "煮てとろみをつける"], "steps": ["豆腐をひと口大に、ねぎを細かく切る。きゅうり・トマトは食べやすく切って別皿へ。ごはんを温める。", "フライパンに油を入れ、ひき肉をほぐして中まで加熱する。ねぎと甘口の焼肉のタレを加え、炒め合わせる。", "豆腐、水200ml、しょうゆ、酢を加え、豆腐が温まるまで煮る。水溶き片栗粉でとろみをつける。唐辛子・ラー油は入れず、野菜を別皿に添える。"]},
{"id": "web-chicken", "category": "簡単定番", "title": "チキンソテーとちぎるだけサラダ", "main": "鶏ももの甘口焼肉だれソテー", "reading": "ちきんそてー", "side": "レタスときゅうり", "time": 20, "image": "/food/dinner-saute.webp", "weeklyLimited": false, "source": {"name": "キッコーマン「チキンソテー」", "url": "https://www.kikkoman.co.jp/homecook/search/recipe/00007224/"}, "ingredients": [{"name": "鶏もも肉", "amount": "2枚（約600g）", "category": "肉"}, {"name": "レタス", "amount": "1/2個", "category": "野菜"}, {"name": "きゅうり", "amount": "1本", "category": "野菜"}, {"name": "甘口の焼肉のタレ", "amount": "大さじ4〜6", "category": "その他"}, {"name": "塩", "amount": "少々", "category": "その他"}, {"name": "油", "amount": "小さじ2", "category": "その他"}, {"name": "炊いたごはん・冷凍ごはん", "amount": "700〜800g", "category": "その他"}], "stepLabels": ["ひと口大に切る", "鶏肉を焼く", "たれをからめる"], "steps": ["鶏肉の厚い部分を開き、ひと口大に切って塩を少しふる。レタスはちぎり、きゅうりは切って別皿に盛る。", "油を入れたフライパンで鶏肉を皮側から焼く。裏返してふたをし、中まで火を通す。重なる場合は分けて焼く。", "余分な脂を取り、焼肉のタレを少なめから加える。焦がさないようからめ、温めたごはんとサラダを添える。"]},
{"id": "web-yakisuki", "category": "牛こま焼き", "title": "牛肉の焼きすき風と蒸し野菜", "main": "薄切り牛肉の甘口だれ焼き", "reading": "ぎゅうにくの やきすきふう", "side": "レンチンキャベツと玉ねぎ", "time": 20, "image": "/food/dinner-yakisuki.webp", "weeklyLimited": false, "source": {"name": "キッコーマン・山本ゆりさん「焼きすき風」", "url": "https://www.kikkoman.co.jp/homecook/search/recipe/00054711/"}, "ingredients": [{"name": "牛薄切り肉", "amount": "400〜500g", "category": "肉"}, {"name": "キャベツ", "amount": "4枚（約200g）", "category": "野菜"}, {"name": "玉ねぎ", "amount": "1個", "category": "野菜"}, {"name": "甘口の焼肉のタレ", "amount": "大さじ4", "category": "その他"}, {"name": "油", "amount": "小さじ2", "category": "その他"}, {"name": "炊いたごはん・冷凍ごはん", "amount": "700〜800g", "category": "その他"}], "stepLabels": ["野菜を切る", "野菜をレンジへ", "牛肉を焼く"], "steps": ["キャベツをざく切り、玉ねぎを薄切りにする。耐熱容器に野菜と水大さじ2を入れ、ふんわりラップをする。", "600Wで約5分、野菜がやわらかくなるまで加熱する。ごはんを温める。野菜は肉に混ぜず別皿へ。", "油を熱したフライパンに牛肉を広げ、中まで焼く。焼肉のタレをからめて盛りつける。生卵は使わず、蒸し野菜と食べる。"]}
];
export const dinnerById=(id:string)=>dinners.find(m=>m.id===id);
export function allowedDinners(data:AppData,date:string){const start=weekStart(date),end=shiftDay(start,6);const used=Object.entries(data.dinner).some(([day,id])=>day!==date&&day>=start&&day<=end&&(id==="manual-curry"||dinnerById(id)?.weeklyLimited));return dinners.filter(m=>(!used||!m.weeklyLimited)&&!data.dislikes.some(x=>x.trim()&&m.ingredients.some(i=>i.name.includes(x.trim()))));}
export function rankDinners(data:AppData,date:string){const pool=allowedDinners(data,date);const recent=Object.entries(data.dinner).filter(([d])=>d<date).sort(([a],[b])=>b.localeCompare(a)).map(([,id])=>id);let seed=0;for(const c of date)seed=seed*31+c.charCodeAt(0)|0;return pool.sort((a,b)=>{const score=(m:Dinner)=> (recent.includes(m.id)?20-recent.indexOf(m.id):0)-(data.favorites.includes(m.id)?2:0)+((dinners.indexOf(m)+Math.abs(seed))%dinners.length)/10;return score(a)-score(b);});}
export function menuText(m:Dinner){return `■ ${m.title}\n主菜：${m.main}\n副菜：${m.side}\n調理時間：約${m.time}分（4人分・炊いたごはん使用）`;}
export function shoppingText(m:Dinner){return ["野菜","肉","その他"].map(c=>`【${c}】\n`+m.ingredients.filter(i=>i.category===c).map(i=>`・${i.name}：${i.amount}`).join("\n")).join("\n\n");}
export function recipePrompt(m:Dinner){return `A4縦の、洗練された料理雑誌風レシピ画像。余白をたっぷりとり、ナチュラルで高級感のある紙面。生成りのリネン、白い陶器、やわらかな自然光。\n献立名「${m.title}」。主菜「${m.main}」を画面中央に大きく、食欲をそそる自然な盛り付けにする。副菜「${m.side}」は別の小皿で添える。ごはんは脇に。実際の材料以外の飾りやソースを足さない。\n材料は4人分。${m.ingredients.map(i=>`${i.name} ${i.amount}`).join("、")}。\n簡単な3つの図解を余白に置く。①${m.stepLabels[0]}：${m.steps[0]} ②${m.stepLabels[1]}：${m.steps[1]} ③${m.stepLabels[2]}：${m.steps[2]}\n「調理時間：約${m.time}分」「4人分」「炊いたごはん使用」を読みやすく小さく配置。料理そのものを主役にし、落ち着いたグリーンと墨色の文字。通常のフライパン・鍋・電子レンジで作る献立。ホットクックは使用しない。`;}

export function nextDinnerSelection(data:AppData,date:string):DinnerSelection|undefined{
 const current=data.suggestions[date];const pool=rankDinners(data,date);if(!current){const first=pool[0];return first?{id:first.id,seen:[first.id],trail:[]}:undefined;}
 const alternatives=pool.filter(m=>m.id!==current.id);if(!alternatives.length)return undefined;
 const unseen=alternatives.filter(m=>!current.seen.includes(m.id));const next=(unseen.length?unseen:alternatives)[0];
 return{id:next.id,seen:unseen.length?[...new Set([...current.seen,next.id])]:[current.id,next.id],trail:[...current.trail,current.id].slice(-99)};
}
