import {z} from "zod";
import type {AppData,LunchMonth} from "./types";
import {validDate} from "./dates";
import {october2026} from "./lunch-2026-10";
export const emptyData=():AppData=>({version:1,revision:0,months:{"2026-10":october2026},dinner:{},suggestions:{},favorites:[],dislikes:[],images:{},shopping:{}});
const date=z.string().refine(validDate,"日付が不正です");
const image=z.string().max(3_000_000).regex(/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/);
const dish=z.object({id:z.string().max(100),name:z.string().min(1).max(120),reading:z.string().max(160),art:z.number().int().min(0).max(63).optional(),image:image.optional()});
const day=z.object({date,status:z.enum(["meal","none","unknown"]),dishes:z.array(dish).max(15),milk:z.boolean().nullable(),event:z.string().max(300),note:z.string().max(500).optional(),confirmed:z.boolean()});
const monthBase=z.object({key:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),name:z.string().max(250),pdf:z.string().max(14_000_000).regex(/^data:application\/pdf;base64,[A-Za-z0-9+/=]+$/).optional(),days:z.record(day),importedAt:z.string().max(100)});
const schema=z.object({version:z.literal(1),revision:z.number().int().nonnegative(),months:z.record(monthBase.extend({previous:monthBase.optional()})),dinner:z.record(z.string().max(80)),suggestions:z.record(z.object({id:z.string().max(80),seen:z.array(z.string()).max(50),trail:z.array(z.string()).max(100)})),favorites:z.array(z.string()).max(100),dislikes:z.array(z.string().max(50)).max(40),images:z.record(image),shopping:z.record(z.array(z.string()).max(100))});
export function validateData(raw:unknown):AppData{const d=schema.parse(raw);for(const[k,m]of Object.entries(d.months)){if(k!==m.key)throw Error("月の情報が一致しません");for(const t of [m,m.previous].filter(Boolean) as LunchMonth[]){for(const[date,day]of Object.entries(t.days)){if(date!==day.date||!date.startsWith(k+"-"))throw Error("日付と月が一致しません");if(day.status==="meal"&&(!day.dishes.length||!day.confirmed))throw Error("未確認の献立が含まれています");}}}return d;}
function openDB(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open("kondate-local",1);r.onupgradeneeded=()=>r.result.createObjectStore("state");r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function readData():Promise<AppData>{const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction("state","readonly");const r=tx.objectStore("state").get("app");r.onsuccess=()=>{try{const loaded=r.result?validateData(r.result):emptyData();
      resolve(loaded.months["2026-10"]?loaded:{...loaded,months:{...loaded.months,"2026-10":october2026}});}catch{reject(Error("保存データを読み込めません。バックアップから復元してください。"));}};r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close();});}
export async function writeData(data:AppData,expectedRevision:number):Promise<AppData>{validateData(data);const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction("state","readwrite");const store=tx.objectStore("state");const get=store.get("app");let failure:Error|null=null;const next={...data,revision:expectedRevision+1};get.onsuccess=()=>{if((get.result?.revision??0)!==expectedRevision){failure=Error("別の画面でデータが更新されました。画面を開き直してください。");tx.abort();return;}store.put(next,"app");};tx.oncomplete=()=>{db.close();resolve(next);};tx.onabort=tx.onerror=()=>{db.close();reject(failure??Error("保存できませんでした。端末の空き容量を確認してください。"));};});}
export function fileDataURL(file:Blob){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(Error("ファイルを読み込めません"));r.readAsDataURL(file);});}
export function downloadJSON(data:AppData){const blob=new Blob([JSON.stringify({kind:"kondate-backup",exportedAt:new Date().toISOString(),data})],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`kondate-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export async function readBackup(file:File){if(file.size>100*1024*1024)throw Error("バックアップは100MB以内にしてください。");const x=JSON.parse(await file.text());if(x.kind!=="kondate-backup")throw Error("このアプリのバックアップを選んでください。");return validateData(x.data);}
export async function readPhoto(file:File){if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw Error("JPEG・PNG・WebPの画像を選んでください。");if(file.size>2*1024*1024)throw Error("画像は2MB以内にしてください。");return fileDataURL(file);}
